language: node_js
cache: yarn
sudo: false
notifications:
  email: false
node_js:
  - '8'
before_install:
  - export CHROME_BIN=chromium-browser
  - npm i -g npm@3 # fix for https://github.com/npm/npm/issues/19222
after_success:
  - yarn build
  - cp .git dist/ -r # required by semantic release
  - cp README.md dist/
  - cd dist
  - yarn install
  - yarn semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
