language: node_js
sudo: required
notifications:
  email: false
node_js:
  - '10'
before_install:
  - if [[ `npm -v` != 6* ]]; then npm i -g npm@6; fi
services:
 - xvfb
addons:
  chrome: stable
after_success:
  - npm run build
  - cp .git dist/@ngx-translate/core/ -r # required by semantic release
  - cp README.md dist/@ngx-translate/core/
  - cd dist/@ngx-translate/core/
  - npm install semantic-release@8.2.3
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
